/* 
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

ANS 4613732
*/

function evenFib(max){
    var i = 1;
    var j = 2;
    var sum = 0;

    while(i < max){
        if(i % 2 == 0){
            sum += i
        }
        var k = i + j;
        i = j;
        j = k;
    }
    return sum
}

module.exports = evenFib